### ISSUE TITLE
postal code change

### ISSUE THREAD

**Issue by vasony** [KAMI911/osm_poi_matchmaker#78]
https://www.openstreetmap.org/node/6752850726

the former problem: addr:postal_code was changed without changing any other parts of address.

**Comment by KAMI911** [comment]
Thank you for taking the time and effort in writing this issue.
If I understand well the problem is with addr:postcode which changed from 1028 to 1029. Since the source of addr:postcode is OpenStreetMap and the related postcode polygon is this: https://www.openstreetmap.org/relation/6886590#map=18/47.54497/18.96223 the code cannot decide if the OSM data is correct.
Based on my fast research the dm is in HÜVI Szolgáltatóház.
References for postcode 1029 are:
https://www.facebook.com/huviszolgaltatohaz/
https://www.openstreetmap.org/relation/6886590
Posta irányítószám kereső: 
Budapest II.
Közterület: Bátori László utca
Irányítószám: 1029

References for postcode 1028 are:
https://www.huvosvolgyhaz.hu/

Budapest II.
Közterület: Hidegkúti út
Irányítószám: 1028

**Comment by vasony** [comment]
First, thank you for the lot of work with this program.

As we discussed before: Please do not change the postal code if other part of the address is not changed, it is so simple.

Since the postal code polygons are not 100% safe, it is ok to create a postal code for a non existing or changed address, but not good enough for correcting them. It can be corrected only from the postal database base.

Assume the postal codes are correct or will be corrected by other QA tools operated by me for **all** the hungarian addresses with valid house numbers. If you change them, it will be an "edit war", and a lot of work for me.
See the history of the presented node. 1029 > 1028  > 1029 > 1028

So the correct workflow

1)  If you are
- creating a new poi or 
- changing its address or
- the postal code is empty
-> you can use the original postal code provided by the data source or determining from the postal code polygon. The present functionality.

2) If the postal code is present and the address is the same as before
- Leave it intact

**Comment by KAMI911** [comment]
Fixed.
